### ISSUE TITLE
webapi & docker-compose

### ISSUE THREAD

**Issue by Julien00859** [EPHEC-TI/WebGames#17]
I cannot mount the volume of the api in the compose because yarn install all the dependencies in a local node_module. I couldn't find a way to tell yarn to install all globally in the dockerfile...

**Comment by Mathieu-R** [comment]
Basically, you don't need to reinstall all the module at each build because we leverage the cache (that's the expected behavior).

In any case, I have **hardcoded** all the folders and files in `docker-compose` then the `node_modules` folder is not erased and you don't have to build every change.

The only time we should build is when we add a new module to node or possibly when we want to build the front end stuff for admin page (rollup).
